Added support for any game type.
The launcher script simplifies launching games with various parameters.

diff --git a/tgm-playback b/tgm-playback
--- a/tgm-playback
+++ b/tgm-playback
@@ -1,14 +1,30 @@
 #!/bin/bash
+if [ ! "$1" ]; then
+    echo "Usage: `basename "$0"` game [tag]"
+    exit 1
+fi
+game="$1"
+shift
+launcher="`which tgm-launcher`"
+[ -f "${launcher:="`dirname "$0"`/tgm-launcher"}" ] \
+    || launcher="`dirname "\`readlink -f "$0"\`"`/tgm-launcher"
+[ ! -f "$launcher" ] && echo 'Unable to find tgm-launcher helper script.' 1>&2 \
+    || . "$launcher"
+
 mameroot="$HOME/.mame"
-nv="$mameroot/nvram/tgm2p.nv"
-inp="$mameroot/inp"
+nv="$mameroot/nvram/$game.nv"
+inp="$mameroot/inp/$game"
 snap="$mameroot/snap"
-meta="$mameroot/meta"
+meta="$mameroot/meta.$game"
 cd "$meta" &>/dev/null
 echo 'Choose an input file:'
-ls
-read -ep '> ' name
-inpfile="$inp/$name.inp"
+if [ ! "$1" ]; then
+    ls
+    read -ep '> ' name
+else
+    name="$1"
+fi
+inpfile="$inp.$name.inp"
 nvfile="$nv.$name"
 metafile="$meta/$name"
 if [ ! -f "$inpfile" ]; then
@@ -32,28 +48,31 @@ else
         seconds="-seconds_to_run $((seconds+1))"
     fi
 fi
-cp "$nvfile" "$snap/tgm2p.nv"
+cp "$nvfile" "$snap/$game.nv"
 echo -n 'Current directory: '
 cd -
 out=''
-read -ep 'Give an output filename if you want to encode: ' -i "$name.mkv" out
+read -ep 'Give an output filename if you want to encode: ' -i "$game.$name.mkv" out
 while [ "$out"x != x -a -e "$out" ]; do
     read -ep "'$out' already exists. Confirm the filename: " -i "$out" out2
     [ "$out2" = "$out" ] && rm -f "$out" && break
     out="$out2"
 done
 if [ "$out" ]; then
-    echo "Choose a crop mode:
-    1  Auto-crop to P1's last game
-    2  Auto-crop to P2's last game
-    Anything else: no auto-crop."
-    read -p ' > ' ac
+    ac=''
+    if [ "$game" = 'tgm2p' ]; then
+        echo "Choose a crop mode:
+        1  Auto-crop to P1's last game
+        2  Auto-crop to P2's last game
+        Anything else: no auto-crop."
+        read -p ' > ' ac
+    fi
 
     echo "Encoding '$name' to '$out'"
     avi="$out.avi"
     avifile="$snap/$avi"
-    trap "rm -f '$avifile' '$snap/tgm2p.nv'" SIGINT
-    tgm $seconds -mt -nothrottle -nosleep -window -resolution 320x240 -nvram_directory 'snap' -playback "$name.inp" -aviwrite "$avi" 2>/dev/null
+    trap "rm -f '$avifile' '$snap/$game.nv'" SIGINT
+    $game $seconds -mt -nothrottle -nosleep -window -resolution 320x240 -nvram_directory 'snap' -playback "$game.$name.inp" -aviwrite "$avi" 2>/dev/null
 
     st=0
     if [ "$ac" ] && [ "$ac" = 1 -o "$ac" = 2 ]; then
@@ -69,7 +88,7 @@ if [ "$out" ]; then
     ffmpeg -i "$avifile" -ss $st -acodec libfaac -ab 96k -vcodec libx264 -vpre normal -crf 20 -threads 0 "$out"
     success=$?
 
-    rm -f "$avifile" "$snap/tgm2p.nv"
+    rm -f "$avifile" "$snap/$game.nv"
     if [ $success = 0 ]; then
         echo "Done encoding '$out'."
     else
@@ -77,7 +96,7 @@ if [ "$out" ]; then
         exit $success
     fi
 else
-    tgm $seconds -nvram_directory 'snap' -playback "$name.inp" 2>/dev/null
-    rm "$snap/tgm2p.nv"
+    $game $seconds -nvram_directory 'snap' -playback "$game.$name.inp" 2>/dev/null
+    rm "$snap/$game.nv"
 fi
 
diff --git a/tgm-record b/tgm-record
--- a/tgm-record
+++ b/tgm-record
@@ -1,14 +1,26 @@
 #!/bin/sh
+if [ ! "$1" ]; then
+    echo "Usage: `basename "$0"` game"
+    exit 1
+fi
+game="$1"
+shift
+launcher="`which tgm-launcher`"
+[ -f "${launcher:="`dirname "$0"`/tgm-launcher"}" ] \
+    || launcher="`dirname "\`readlink -f "$0"\`"`/tgm-launcher"
+[ ! -f "$launcher" ] && echo 'Unable to find tgm-launcher helper script.' 1>&2 \
+    || . "$launcher"
+
 mameroot="$HOME/.mame"
-nv="$mameroot/nvram/tgm2p.nv"
-inp="$mameroot/inp"
-meta="$mameroot/meta"
+nv="$mameroot/nvram/$game.nv"
+inp="$mameroot/inp/$game"
+meta="$mameroot/meta.$game"
 name="`date '+%Y%m%d.%H%M'`"
 [ -d "$meta" ] || mkdir "$meta" || echo 'Unable to create metadata directory. Record length will not be saved.'
 cp "$nv" "$nv.$name"
 echo "Recording $name..."
-seconds="`tgm -record "$name.inp" "$@" 2>/dev/null | awk '/^Average speed:/ {print substr($4,2)}'`"
-echo "Recorded $seconds seconds of input."
+seconds="`$game -record "$game.$name.inp" "$@" 2>/dev/null | awk '/^Average speed:/ {print substr($4,2)}'`"
+echo "Recorded ${seconds:="0"} seconds of input."
 if [ -t 0 ]; then
     read -p 'Give a name, or leave blank to discard: ' tag
 else
@@ -16,12 +28,12 @@ else
 fi
 if [ "$tag" ]; then
     mv "$nv.$name" "$nv.$name.$tag"
-    mv "$inp/$name.inp" "$inp/$name.$tag.inp"
+    mv "$inp.$name.inp" "$inp.$name.$tag.inp"
     echo "$seconds" > "$meta/$name.$tag"
     echo "Saved as '$name.$tag'"
 else
     mv "$nv.$name" "$nv.discarded"
-    mv "$inp/$name.inp" "$inp/discarded.inp"
+    mv "$inp.$name.inp" "$inp.discarded.inp"
     echo "$seconds" > "$meta/discarded"
     echo "Discarded."
 fi
